- name: Install dependencies
  apt: name={{ item }} update_cache=true state=latest
  with_items:
  - openssl
  - libssl-dev
  - libssl-doc
  tags:
  - postgres
 
- name: Install Postgres
  apt: name={{ item }} update_cache=true state=present
  with_items:
  - postgresql
  - postgresql-contrib
  - libpq-dev
  - python3-psycopg2
  tags:
  - postgres

- name: Ensure Postgres service is running
  service: name=postgresql state=started enabled=yes
  tags:
  - postgres

# Configuring database and database users

- name: Creating database
  become: yes
  become_user: postgres
  postgresql_db: name={{ db_name }} state=present
  tags:
  - postgres

- name: Creating database user
  become: yes
  become_user: postgres
  postgresql_user: state=present name={{ db_user }} password={{ db_password }}
  tags:
  - postgres

- name: Provide user access to database
  become: yes
  become_user: postgres
  postgresql_privs:
     type: database
     database: "{{ db_name }}"
     roles: "{{ db_user }}"
     grant_option: no
     privs: all 
  tags:
  - postgres

- name: "Allow md5 connection for the db user"
  postgresql_pg_hba:
    dest: "/etc/postgresql/12/main/pg_hba.conf"
    contype: local
    databases: all
    method: md5
    users: "{{ db_user }}"
    create: true
  become: yes
  become_user: postgres
  notify: restart postgres
  tags:
  - postgres